language: php

sudo: false

php:
  - '5.5'
  - '5.6'
  - '7.0'

script:
  - phpunit --coverage-text
  - ls -al bin/
  - composer check

before_script:
  - composer install --no-interaction  --ignore-platform-reqs --no-scripts

cache:
    directories:
    - vendor/