app:
    resource: "@JirasticBundle/Controller/"
    type:     annotation

jirastic_routing:
    resource: "@JirasticBundle/Resources/config/routing.xml"
    prefix: /

jirastic_board:
    resource: "@JirasticBundle/Controller/BoardController.php"
    type:     annotation
