<?php

namespace JirasticBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CustomfieldRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomfieldRepository extends EntityRepository
{
}
